Add missing jinja templating module
Revision 16 added contrib.templating.jinja to the
charm-helpers-sync.yaml but did not commit the module to the tree.
Installing the ntp charm fails with the following traceback:

 Traceback (most recent call last):
   File "/var/lib/juju/agents/unit-ntp-3/charm/hooks/install", line 8, in <module>
     from charmhelpers.contrib.templating.jinja import render
 ImportError: No module named contrib.templating.jinja